EMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using EMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using static Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions;

namespace EMS.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly ILogger<HomeController> logger;
        private readonly EMSContext context;
        private readonly UserManager<Admin> userManager;

        public EmployeeController(ILogger<HomeController> logger, EMSContext context, UserManager<Admin> userManager)
        {
            this.logger = logger;
            this.context = context;
            this.userManager = userManager;
        }

        public IActionResult Allemployees()
        {
            try
            {
                logger.LogDebug("Showing Allemployees()");
                List<Employee> employees = context.Employee.ToList();
                ViewData["employees"] = employees;
                return View();
            }
            catch (Exception e)
            {
                LogException(e);
                logger.LogError("Error showing AllEmployees", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult ActiveEmployees()
        {
            try
            {
                logger.LogDebug("Showing ActiveEmployees()");
                List<Employee> employees = context.Employee.Where(emp => emp.Status == true).ToList();
                ViewData["employees"] = employees;
                return View();
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error showing ActiveEmployees", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult OrariEmployees()
        {
            try
            {
                logger.LogDebug("Showing ActiveEmployees()");
                List<Employee> employees = context.Employee.Where(emp => emp.Status == true).ToList();
                ViewData["employees"] = employees;
                return View();
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error showing ActiveEmployees", e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public IActionResult Regjistro(Employee employee)
        {
            try
            {
                logger.LogDebug("Regjistro()");
                if (ModelState.IsValid)
                {
                    employee.Status = true;

                    context.Entry(employee).Property("CreatedBy").IsModified = false;
                    context.Entry(employee).Property("DateCreated").IsModified = false;

                    context.Employee.Add(employee);
                    context.SaveChanges();
                    logger.LogDebug("New Employee was created by " + User.Identity.Name);
                    TempData["registered"] = true;
  
                    context.Logs.Add(new Logs { 
                        mesazhi = $"Employee {employee.FirstName} {employee.LastName} was added with id: {employee.Id}", 
                        createdBy = User.FindFirst(ClaimTypes.NameIdentifier).Value, 
                        createdAt = DateTime.Now });
                    context.SaveChanges();

                    return RedirectToAction("Allemployees");
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error creating new Employee", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult ShfaqKontraten() {
            return View();          
        }
        [HttpPost]
        public IActionResult ShfaqKontraten(Employee employee)
        {
            try
            {
                logger.LogDebug("ShfaqKontraten()");
                if (ModelState.IsValid)
                {                  
                    return View(employee);
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error creating new Employee", e);
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult Kontrollo(int id)
        {
            try
            {
                logger.LogDebug("Kontrollo {id}", id);
                Employee employee = context.Employee.Include(e => e.Attendance).First(e => e.Id == id);
                ViewData["employee"] = employee;
                return View();
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error getting details for {id}", id);
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult ChangeOrari(int id)
        {
            Employee employee = context.Employee.Find(id);
            if(employee.Schedule == "Pasdite")
            {
                employee.Schedule = "Paradite";
            }
            else
            {
                employee.Schedule = "Pasdite";
            }

            context.Logs.Add(new Logs
            {
                mesazhi = $"Orari u ndryshua ne {employee.Schedule} per punetorin {employee.FirstName} me id {employee.Id}",
                createdBy = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                createdAt = DateTime.Now
            });
            context.SaveChanges();

            return RedirectToAction("OrariEmployees");
        }

        public IActionResult Update(int id)
        {
            try
            {
                logger.LogDebug("ShowEmployee({id})", id);
                Employee employee = context.Employee.Find(id);
                if (employee == null)
                {
                    return NotFound();
                }

                ViewData["updated"] = false;
                return View(employee);
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error getting details for {id}", id);
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public IActionResult Update(Employee employee)
        {
            try
            {
                logger.LogDebug("Update()");
                if (ModelState.IsValid)
                {
                    context.Employee.Update(employee);
                    context.Entry(employee).Property("CreatedBy").IsModified = false;
                    context.Entry(employee).Property("DateCreated").IsModified = false;

                    context.Logs.Add(new Logs
                    {
                        mesazhi = $"Te dhenat u ndryshuan per punetorin {employee.FirstName} me id {employee.Id}",
                        createdBy = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                        createdAt = DateTime.Now
                    });

                    context.SaveChanges();

                    logger.LogDebug("Emplyee with id: {id} was updated by: {name}", employee.Id, User.Identity.Name);
                    ViewData["updated"] = true;
                    return View(employee);   
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error updating Employee with id: {id}", employee.Id, e);
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                Employee emp = context.Employee.Find(id);
                if (emp == null)
                {
                    return BadRequest();
                }
                context.Employee.Remove(emp);
                context.SaveChanges();

                logger.LogInformation("Employee with id: {id} was fired by {name}", emp.Id, User.Identity.Name);

                return RedirectToAction("AllEmployees");
            }catch(Exception e)
            {
                LogException(e);

                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult KtheNePune(int id)
        {
            try
            {
                logger.LogDebug("KtheNePune()");
                Employee employee = context.Employee.Find(id);
                employee.Status = true;

                context.Entry(employee).Property("CreatedBy").IsModified = false;
                context.Entry(employee).Property("DateCreated").IsModified = false;

                context.Logs.Add(new Logs
                {
                    mesazhi = $"Statusi per punetorin {employee.FirstName} u ndryshua",
                    createdBy = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                    createdAt = DateTime.Now
                });

                context.SaveChanges();

                logger.LogInformation("Employee with id: {id} was employed again by {name}", employee.Id, User.Identity.Name);

                return RedirectToAction("Allemployees");
            }
            catch (Exception e)
            {
                LogException(e);

                logger.LogError("Error employing again Employee with id: {id}");

EMS/Views/Shared/Partials/FshijModal.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Kujdes!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Jeni sigurt qe deshironi ta perfundoni kete veprim?!
                <form method="post" id="deleteEmp" asp-controller="Employee" asp-action="Delete">
                    <input type="hidden" id="id" name="id" value="">
                    <input type="hidden" id="returnUrl" name="returnUrl"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Anulo</button>
                <button type="submit" form="deleteEmp" class="btn btn-primary btn-danger">Fshij</button>
            </div>
        </div>
    </div>
</div>

EMS/Views/Shared/Partials/KontrolloModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<!-- Modal -->
<div class="modal fade" id="kontrolloModal" tabindex="-1" role="dialog" aria-labelledby="kontrolloModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kontrolloModalTitle">Kujdes!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Ju lutem afroni kartelen e punetorit aktiv ne RFID Scanner!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Mbyll</button>
                <a class="btn btn-primary" asp-controller="Employee" asp-action="Kontrollo" asp-route-id="1" role="button">Kontrollo</a>
            </div>
        </div>
    </div>
</div>

EMS/Views/Shared/Partials/RaportetModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<!-- Modal -->
    <div class="modal fade" id="raportModal" tabindex="-1" role="dialog" aria-labelledby="raportModalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <img src="~/template/dist/img/ubtlogo.png" alt="EMS logo" class="brand-image img-circle elevation-3"
                         style="opacity: .8">
                    <h5 class="modal-title" id="raportetModalTitle">Gjenero Raporte</h5>
                </div>
                <div class="modal-body flex-column">
                        <button type="button" class="btn btn-primary btn-lg btn-block">Raporti Ditor</button>
                        <button type="button" class="btn btn-primary btn-lg btn-block">Raporti Javor</button>
                        <button type="button" class="btn btn-primary btn-lg btn-block">Raporti Mujor</button>
                        <button type="button" class="btn btn-primary btn-lg btn-block">Raporti Vjetor</button>            
                </div>
            </div>
        </div>
    </div>

EMS/Views/Shared/Partials/RegisterModal.cshtml
@model EMS.Models.Employee
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<!-- Modal -->
<div class="modal fade" id="regjistroModal" tabindex="-1" role="dialog" aria-labelledby="regjistroModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="regjistroModalTitle">Kujdes!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Ju lutem afroni kartelen ne RFID Scanner!
                <div class="collapse" id="collapseExample">
                    <form id="registerForm" method="post" asp-controller="Employee" asp-action="ShfaqKontraten">
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label asp-for="PersonalNumber">Numri Personal</label>
                                <input asp-for="PersonalNumber" type="number" class="form-control" id="personalNumber" placeholder="123xxxxxxxx">
                                <span asp-validation-for="PersonalNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="FirstName">Emri</label>
                                <input asp-for="FirstName" type="text" class="form-control id="firstName" placeholder="Filan">
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="LastName">Mbiemri</label>
                                <input asp-for="LastName" type="text" class="form-control" id="lastName" placeholder="Fisteku">
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="Birthday">Ditelindja</label>
                                <input asp-for="Birthday" type="date" class="form-control" id="birthday">
                                <span asp-validation-for="Birthday" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="Email">Email</label>
                                <input asp-for="Email" type="email" class="form-control" id="email" placeholder="email@example.com">
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="PhoneNumber">Numri Telefonit</label>
                                <input asp-for="PhoneNumber" type="number" class="form-control" id="phoneNumber" placeholder="+383 (0) 44 xxx xxx">
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputGender">Gjinia</label>
                                <select asp-for="Gender" id="gender" class="form-control">
                                    <option selected value="">Zgjidh...</option>
                                    <option value="m">Mashkull</option>
                                    <option value="f">Femer</option>
                                </select>
                                <span asp-validation-for="Gender" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="Banka">Banka</label>
                                <select asp-for="Banka" id="banla" class="form-control">
                                    <option selected value="">Zgjidh...</option>
                                    <option value="Teb">TEB</option>
                                    <option value="Bkt">BKT</option>
                                    <option value="Bpb">BPB</option>
                                    <option value="Raiffeisen">Raiffeisen</option>
                                    <option value="BankaEkonomike">BankaEkonomike</option>
                                    <option value="ProCredit">ProCredit</option>
                                </select>
                                <span asp-validation-for="Banka" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="NrBankes">Numri i Gjirollogarise</label>
                                <input asp-for="NrBankes" type="number" class="form-control" id="nrbankes" placeholder="xxxxxxxxxxxxxxxxxx">
                                <span asp-validation-for="NrBankes" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label asp-for="City">Qyteti</label>
                                <input asp-for="City" type="text" class="form-control" id="inputCity" placeholder="Prizren">
                                <span asp-validation-for="City" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputState">Shteti</label>
                                <select asp-for="State" id="state" class="form-control">
                                    <option selected value="">Zgjidh...</option>
                                    <option value="Kosove">Kosove</option>
                                    <option value="Shqiperi">Shqiperi</option>
                                    <option value="Mali i Zi">Mali i Zi</option>
                                    <option value="Maqedoni">Maqedoni</option>
                                </select>
                                <span asp-validation-for="State" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="Holiday">Pushimi</label>
                                <select asp-for="Holiday" id="holiday" class="form-control">
                                    <option value="E hene">E hene</option>
                                    <option value="E marte">E marte</option>
                                    <option value="E merkure">E merkure</option>
                                    <option value="E ejte">E ejte</option>
                                    <option value="E premte">E premte</option>
                                    <option value="E shtune">E shtune</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label asp-for="Position">Pozita</label>
                                <input asp-for="Position" type="text" class="form-control" id="position" placeholder="Menaxher">
                                <span asp-validation-for="Position" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputSchedule">Orari</label>
                                <select asp-for="Schedule" id="schedule" class="form-control">
                                    <option selected value="">Zgjidh...</option>
                                    <option value="Paradite">Paradite</option>
                                    <option value="Pasdite">Pasdite</option>
                                </select>
                                <span asp-validation-for="Schedule" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="PaymentPerHour">Pagesa per ore</label>
                                <input asp-for="PaymentPerHour" type="text" class="form-control" id="paymentperHour" placeholder="1.5">
                                <span asp-validation-for="PaymentPerHour" class="text-danger"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Gjenero</button>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Mbyll</button>
                <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample">Vazhdo</button>

            </div>
        </div>
    </div>
</div>